name: Build Projects

on:
  push:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: alpine:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: apk add --no-cache cmake make gcc g++

    - name: Build project 01_vcs
      working-directory: 01_vcs
      run: |
        mkdir build
        cd build
        cmake ..
        make
